version: '3'
volumes:
  jenkins-data:
  dependency-track:
  pact-db-volume:

services:
  dtrack-apiserver:
    platform: linux/arm64
    image: dependencytrack/apiserver:snapshot
    ports:
      - '18081:8080'
    volumes:
      - 'dependency-track:/data'
    restart: unless-stopped
  dtrack-frontend:
    image: dependencytrack/frontend
    depends_on:
      - dtrack-apiserver
    environment:
      - API_BASE_URL=http://localhost:18081
    ports:
      - "18082:8080"
    restart: unless-stopped  
  jenkins:
    build: ./jenkins
    restart: always
    ports:
      - "18080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - jenkins-data:/var/lib/jenkins/
    depends_on:
      - sonar
    environment:
      - SONAR_PORT=9000
      - SONAR_DB_PORT=5432
  pact-db:
    platform: linux/x86_64
    image: postgres
    healthcheck:
      test: psql postgres --command "select 1" -U postgres
    volumes:
      - pact-db-volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres  
  pact-broker:
    image: pactfoundation/pact-broker
    restart: always
    ports:
      - "19292:9292"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - jenkins-data:/var/lib/jenkins/
    depends_on:
      - pact-db
    environment:
      - PACT_BROKER_DATABASE_USERNAME=postgres
      - PACT_BROKER_DATABASE_PASSWORD=password
      - PACT_BROKER_DATABASE_HOST=pact-db
      - PACT_BROKER_DATABASE_NAME=postgres
      - PACT_BROKER_WEBHOOK_SCHEME_WHITELIST=http https
  sonardb:
    platform: linux/x86_64
    image: postgres:9.6
    restart: always
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - ./sonar/db:/var/lib/postgresql/data
  sonar:
    image: sonarqube-arm:latest
    restart: always
    ports:
      - "19000:9000"
      - "19092:9092"
    depends_on:
      - sonardb
    volumes:
      - ./sonar/data:/opt/sonarqube/data
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://sonardb:5432/sonar
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar
      - SONARQUBE_ADMIN_PASSWORD=admin
